"""Turn pnach groups on and off in a running game, with no reboot.

PCSXROO's ``patch.reload`` takes the *enabled* list from the settings loaded at
boot, so this renames groups in the pnach: one whose header no longer matches an
enabled name is not applied.

Removing a patch does not undo it: ``patch=1`` lines are rewritten every frame, so
the last value stays in RAM. Disabling therefore also restores the original words
from the boot ELF (zero outside any ELF segment, i.e. the trampoline zone).

    python tools/patchctl.py --status
    python tools/patchctl.py --off                 # stock 60fps, no compensation
    python tools/patchctl.py --on shipped          # the five shipped groups
    python tools/patchctl.py --on air              # shipped plus the airborne work
    python tools/patchctl.py --on "60FPS - battle"
"""

from __future__ import annotations

import argparse
from pathlib import Path

import _bootstrap  # noqa: F401

from game import config
from ps2ee.eemem import ElfImage
from ps2ee.pnach import Pnach
from ps2ee.roo import Roo

# The five proven groups already in the user's PCSX2.
SHIPPED = [
    "60FPS - battle",
    "60FPS - animation clock",
    "60FPS - input repeat timing",
    "60FPS - input timing",
    "60FPS - aura update rate",
]

# The airborne work, under test.
AIRBORNE = [
    "60FPS - airborne motion",
    "60FPS - airborne vertical",
    "60FPS - airborne residual",
    "60FPS - gravity",
]

# Fighter-model effect rotation, halved in an airborne hover.
EFFECTS = ["60FPS - effect rotation"]

# Tween system: the 30.0 seconds-to-frames constant becomes 60.0.
TWEENS = ["60FPS - tween duration"]

# Particle system: caller's update gated on frame parity.
PARTICLES = ["60FPS - particle update rate"]

# Hovering idle bob: halved phase step.
HOVER = ["60FPS - hover bob"]

# Blast hit cadence: hitbox tick counter gated on frame parity.
BLAST = ["60FPS - blast hit cadence"]

# Blast visual effects: both effect-node updates gated on frame parity.
BLASTFX = ["60FPS - blast effect rate"]

# Blast sequence rate: the action controller's dispatch gated for one class.
SEQ = ["60FPS - blast sequence rate"]

# Blast effect duration. These steps cannot be gated, only slowed, and all
# nineteen must be halved together.
BLASTDUR = ["60FPS - blast effect duration"]

# Scripted-sequence clock: waits count down on even ticks only.
SEQWAIT = ["60FPS - sequence wait"]

# Fighter state-machine phase timers (generated by tools/mkgate.py). A site is a
# clock only if the instruction after its add compares it; gating an index into a
# table freezes a fighter in its state.
PHASE = ["60FPS - state phase timers"]

# Hard Knockback and Lightning Attack: phase timers and the pursuit intercept.
PURSUIT = ["60FPS - knockback flight", "60FPS - pursuit timing"]

# Camera: blend rate and scripted-move countdown. One group, because neither half
# is correct alone.
CAMERA = ["60FPS - camera pacing"]

# Cinematic camera clip time step 2.0 becomes 1.0.
CINECAM = ["60FPS - cinematic camera"]

# Transformation loader: answered "not ready" on odd ticks.
TRANSLOAD = ["60FPS - transformation load"]

# Spare names for future groups; the ini's enabled list is only read at boot.
SPARES = ["60FPS - spare 1", "60FPS - spare 2", "60FPS - spare 3"]

# What the ini enables. A group must carry one of these names to apply at all, and
# the list changes only by restarting the emulator.
# Cut-in keyframe clock: track clock rate 2.0 becomes 1.0.
MOUTH = ["60FPS - mouth clock"]

# Projectile travel: effect-node position integrator step halved. Changes how the
# game plays (time to dodge).
PROJECTILE = ["60FPS - projectile travel"]
OBJFLIGHT = ["60FPS - blast object travel"]
BEAMFLIGHT = ["60FPS - beam object travel"]

# Fullscreen fade node: all three phases counted per tick.
SCREENFADE = ["60FPS - screen fade"]

# Thrown objects (Hercule's blasts): whole update on even ticks.
THROWN = ["60FPS - thrown object rate"]

# Solar Flare: the victim's blind timer and flash step on even ticks.
SOLARFLARE = ["60FPS - solar flare"]

# Rush Struggle: only the AI's synthetic stick is gated.
STRUGGLE = ["60FPS - rush struggle"]

# Beam Struggle: event-manager phases back on real time; only the AI rotation is gated.
BEAMCLASH = ["60FPS - beam clash"]

# Stage scenery: keyframe time advance 2.0 becomes 1.0 (not every map has any).
STAGE = ["60FPS - stage animation"]

# Two effect classes counting 30Hz ticks: scripted effect tracks and the
# transformation flash.
FXTRACK = ["60FPS - effect track clock"]
TRANSFLASH = ["60FPS - transformation flash"]

# Rushing Blast 2 time limit: the 30.0 constant becomes 60.0.
RUSHLIMIT = ["60FPS - rushing Blast 2 time limit"]

ENABLED_IN_INI = (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES
                  + HOVER + BLAST + BLASTFX + SEQ
                  + BLASTDUR + SEQWAIT + PHASE + PURSUIT + CAMERA + MOUTH
                  + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE
                  + STRUGGLE + BEAMCLASH + STAGE + SOLARFLARE + THROWN + CINECAM
                  + TRANSLOAD + FXTRACK + TRANSFLASH + RUSHLIMIT
                  + SPARES)

PRESETS = {
    "off": [],
    "shipped": SHIPPED,
    "air": SHIPPED + AIRBORNE + EFFECTS,
    "tween": SHIPPED + AIRBORNE + EFFECTS + TWEENS,
    "noblast": SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER,
    "nofx": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
             + BLAST),
    "noseq": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
              + BLAST + BLASTFX),
    # BLASTFX and SEQ are both WITHDRAWN, for the same underlying reason: an
    # effect that is gated is an effect that does not get built. BLASTFX skips
    # the geometry rebuild; SEQ skips the controller step that SPAWNS the
    # effects, so a charged blast renders nothing at all and deals no damage.
    # SEQ looked innocent only because it was tested with an uncharged tap,
    # which never exercises the charge path. Both stay in the pnach as a record.
    "withseq": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                + BLAST + BLASTDUR + SEQ),
    "noseqwait": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                  + BLAST + BLASTDUR + PHASE),
    "nophase": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                + BLAST + BLASTDUR + SEQWAIT),
    # PHASE was WITHDRAWN 2026-09-07 and reinstated 2026-09-16. It gated 22
    # counters inside the fighter state machine - the exact mechanism behind a
    # fighter that fails to leave a state - and every one of them was scored
    # against two GROUNDED oracles, a held charge and a mashed rush. No airborne
    # state was ever tested, and the user hit a repeatable trap in state 157
    # (FUN_001E6DC8) with no pending transition.
    #
    # Reading the binary closed part of that hole, not all of it
    # - 001E6F40 is an index into a table instead of a count of frames,
    # and it is inside FUN_001E6DC8 itself. Four more indices came out after
    # #39, and PHASE now gates 17 clocks.
    "withphase": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                  + BLAST + BLASTDUR + SEQWAIT + PHASE),
    # SEQWAIT was withdrawn briefly on 2026-09-07 to isolate the state 157 trap,
    # then RESTORED once the user confirmed the trap did not follow it out: the
    # 15-group set still trapped nothing but the ultimate ended early again.
    # It is confirmed-good in play and does not touch state transitions.
    "noseqwait2": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                   + BLAST + BLASTDUR),
    # The 16-group set that was confirmed good in play, kept so the pursuit
    # work has a named baseline to be diffed against without editing a preset.
    "nopursuit": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                  + BLAST + BLASTDUR + SEQWAIT),
    # The 18-group set v13 shipped, kept so the camera work has a named
    # baseline to be diffed against without editing a preset.
    "nocamera": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                 + BLAST + BLASTDUR + SEQWAIT + PURSUIT),
    "nomouth": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA),
    "noproj": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
               + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH),
    "full": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
             + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
             + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
             + BEAMCLASH + PHASE + STAGE + SOLARFLARE + THROWN + CINECAM
             + TRANSLOAD + FXTRACK + TRANSFLASH + RUSHLIMIT),
    # "full" without the rush time limit, so that group has a named baseline.
    "norushlimit": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                    + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                    + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                    + BEAMCLASH + PHASE + STAGE + SOLARFLARE + THROWN + CINECAM
                    + TRANSLOAD + FXTRACK + TRANSFLASH),
    # "full" without the two effect clocks, so those groups have a named baseline.
    "nofxclock": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                  + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                  + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                  + BEAMCLASH + PHASE + STAGE + SOLARFLARE + THROWN + CINECAM
                  + TRANSLOAD),
    # "full" without the transformation load, so that group has a named baseline.
    "notransload": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                    + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                    + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                    + BEAMCLASH + PHASE + STAGE + SOLARFLARE + THROWN + CINECAM),
    # "full" without the cinematic camera, so that group has a named A/B baseline.
    "nocinecam": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                  + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                  + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                  + BEAMCLASH + PHASE + STAGE + SOLARFLARE + THROWN),
    # "full" without the thrown objects, so that group has a named A/B baseline.
    "nothrown": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                 + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                 + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                 + BEAMCLASH + PHASE + STAGE + SOLARFLARE),
    # "full" without the stage animation, kept so the new group has a named
    # baseline to be diffed against without editing a preset.
    "nostage": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                + BEAMCLASH + PHASE + SOLARFLARE + THROWN),
    # "full" without Solar Flare, so that group has a named A/B baseline.
    "noflare": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                + BEAMCLASH + PHASE + STAGE + THROWN),
    # "full" without the phase timers, kept so the reinstated group has a named
    # baseline to be diffed against without editing a preset.
    "nophase2": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
                 + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
                 + PROJECTILE + OBJFLIGHT + BEAMFLIGHT + SCREENFADE + STRUGGLE
                 + BEAMCLASH + STAGE + SOLARFLARE + THROWN),
    # The 21-group set without the fade, so the fade has a named A/B baseline.
    "nofade": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
               + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
               + PROJECTILE + OBJFLIGHT + BEAMFLIGHT),
    "nobeam": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
               + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
               + PROJECTILE + OBJFLIGHT),
    "noobj": (SHIPPED + AIRBORNE + EFFECTS + TWEENS + PARTICLES + HOVER
              + BLAST + BLASTDUR + SEQWAIT + PURSUIT + CAMERA + MOUTH
              + PROJECTILE),
}

DISABLED_SUFFIX = " [off]"


def _base_name(name: str) -> str:
    return name[: -len(DISABLED_SUFFIX)] if name.endswith(DISABLED_SUFFIX) else name


def read_pnach() -> tuple[Path, Pnach]:
    path = config.roo_cheat_file()
    return path, Pnach.load(path)


def status() -> None:
    path, pnach = read_pnach()
    print(path)
    for group in pnach.groups:
        name = _base_name(group.name)
        on = group.name == name and name in ENABLED_IN_INI
        print(f"  [{'ON ' if on else 'off'}] {name}  ({len(group.lines)} lines)")
    warn_unenabled(pnach)


def warn_unenabled(pnach=None) -> list[str]:
    """Groups the emulator will ignore however correct the pnach is.

    PCSXROO reads its [Cheats] Enable list at boot from its OWN per-game ini, not the
    installed PCSX2's. A group missing there applies nothing and says nothing, so the
    measurement quietly scores the unpatched game.
    """
    try:
        enabled = config.roo_enabled_cheats()
    except FileNotFoundError:
        return []
    if not enabled:
        return []
    if pnach is None:
        _, pnach = read_pnach()
    present = {_base_name(g.name) for g in pnach.groups}
    missing = [n for n in ENABLED_IN_INI if n in present and n not in enabled]
    if missing:
        print("")
        print(f"  !! not enabled in {config.roo_game_ini()}")
        for name in missing:
            print(f"     {name}")
        print("     Add an 'Enable = <name>' line there and RESTART the emulator;")
        print("     until then these groups apply nothing at all.")
    return missing


def original_word(elf: ElfImage, addr: int) -> int:
    """What was at this address before any patch touched it."""
    return elf.u32(addr) if elf.segment_for(addr) else 0


def apply(roo: Roo, wanted: list[str], quiet: bool = False) -> None:
    """Make exactly ``wanted`` active, and restore what the rest overwrote.

    **An enabled group is not in RAM when this returns**: the cheat engine writes it
    at a frame boundary. Advance a few frames before reading a patched address or
    arming a breakpoint, or every arm silently measures the unpatched game.
    """
    path, pnach = read_pnach()
    elf = ElfImage.load(config.elf_path())

    restore: dict[int, int] = {}
    for group in pnach.groups:
        name = _base_name(group.name)
        group.name = name if name in wanted else name + DISABLED_SUFFIX
        if name not in wanted:
            for line in group.lines:
                if not line.is_condition and line.width == 4:
                    restore[line.target] = original_word(elf, line.target)
    path.write_text(pnach.render(), encoding="utf-8")

    # Reload first so the cheat engine stops rewriting these words, then restore the
    # originals; otherwise the next frame re-applies the patch.
    roo.patch_reload()

    failed = []
    for addr, word in sorted(restore.items()):
        if not roo.write(addr, word):
            failed.append(addr)
    if failed:
        raise RuntimeError(
            "these words did not stay written, so something is still patching "
            "them: " + ", ".join(f"{a:08X}" for a in failed))
    if not quiet:
        print(f"active: {', '.join(wanted) if wanted else '(none)'}"
              f"   restored {len(restore)} words")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--status", action="store_true")
    parser.add_argument("--off", action="store_true")
    parser.add_argument("--on", nargs="*", default=None,
                        help='group names, or a preset: ' + ", ".join(PRESETS))
    args = parser.parse_args()

    if args.status or (not args.off and args.on is None):
        status()
        return 0

    wanted: list[str] = []
    if args.on:
        for name in args.on:
            wanted += PRESETS.get(name, [name])
    apply(Roo().connect(), wanted)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
